name: Build (Windows)

on:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'source/*'
      - '.github/workflows/windows.yml'
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: ''

jobs:
  build-windows:
    runs-on: windows-2025

    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v7
      with:
        submodules: true

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Ninja
      run: pip install ninja

    - name: Cache CUDA
      id: cache-cuda
      uses: actions/cache@v6
      with:
        path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA
        key: ${{ runner.os }}-cuda-13.4.2

    - name: Setup CUDA
      if: steps.cache-cuda.outputs.cache-hit != 'true'
      run: |
        curl -s -o cuda_installer.exe -L https://developer.download.nvidia.com/compute/cuda/13.4.2/network_installers/cuda_13.4.2_windows_x86_64_network.exe
        cuda_installer.exe -s nvcc_13.4 cudart_13.4 nvrtc_dev_13.4 crt_13.4 nvptxcompiler_13.4 nvvm_13.4

    - name: Download VapourSynth headers
      run: |
        curl -s -o vs.zip -L https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth-*/ vapoursynth/

    - name: Configure
      run: cmake -S . -B build_cuda -G Ninja -LA
        -D CMAKE_BUILD_TYPE=Release
        -D VS_INCLUDE_DIR="%cd%\vapoursynth\include"
        -D CMAKE_CXX_FLAGS="/fp:fast /EHsc"
        -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
        -D CMAKE_CUDA_FLAGS="--threads 0 --use_fast_math --resource-usage -Wno-deprecated-gpu-targets"
        -D CMAKE_CUDA_ARCHITECTURES="75;86-real;89-real;120-real"
      env:
        CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.4

    - name: Build
      run: cmake --build build_cuda --verbose

    - name: Install
      run: cmake --install build_cuda --prefix install

    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: vs-nlm-cuda-windows
        path: install/bin/*.dll

    - name: Compress artifact for release
      if: github.event_name == 'workflow_dispatch' && inputs.tag != ''
      run: |
        mkdir vs-nlm-cuda-windows-${{ inputs.tag }}
        copy install\bin\vsnlm_cuda.dll vs-nlm-cuda-windows-${{ inputs.tag }}\
        7z a -t7z -mx=9 vs-nlm-cuda-windows-${{ inputs.tag }}.7z vs-nlm-cuda-windows-${{ inputs.tag }}

    - name: Upload release assets
      if: github.event_name == 'workflow_dispatch' && inputs.tag != ''
      uses: actions/upload-artifact@v7
      with:
        name: release-assets
        path: vs-nlm-cuda-windows-${{ inputs.tag }}.7z

  build-wheel:
    name: Package Wheel (Windows)
    needs: build-windows
    uses: ./.github/workflows/wheel.yml
    with:
      os: windows-2025
      artifact_name: vs-nlm-cuda-windows
      artifact_path: install/bin
      build_sdist: false
